Ea 3619 add workflows
europeana/translation-api pull request #34
Opened 2023-12-01 14:58 UTC by SrishtiSingh-eu

2023-12-13 16:09 UTC, gsergiu requested changes

2023-12-13 16:09 UTC, gsergiu commented on translation-client/pom.xml
> +            <artifactId>corelib-definitions</artifactId>
is this dependency required?

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/config/TranslationClientConfiguration.java
> +        try { properties = new Properties();
should use try with resource

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/exception/TranslationApiException.java
> +        return HttpStatus.INTERNAL_SERVER_ERROR;
I don't think that client exceptions should indicate a 500 error. We should also not make the clients dependent on the server side code. The API-Commons is dpendent on server side (web-mvc)

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/model/TranslationMap.java
> +public class TranslationMap extends LinkedHashMap<String, List<String>> {
This structure is not able to represent fileds that have values in multiple languages. Probably not a concern for now, but for forward compatibility I would recommend using LinkedHashMap<String, List<TranslationObj>>.  TranslationObj contains allready both the source and the target languages.

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/model/TranslationMap.java
> +    public TranslationMap translate(TranslationApiClient translationApiClient, String targetLanguage) throws TranslationApiException {
I think this method is better placed in the TransationApiClient. TranslationMap should stay as a POJO without business logic

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/model/TranslationMap.java
> +        for (Map.Entry<String, Integer> entry : textsPerField.entrySet()) {
Not clear what this for loop does, however, if we switch to use List<TranslationObj>, streams can be used for performing any kind of filtering. The use of Map<String, Integer> textsPerField seems to be an overcomplication

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/model/TranslationMap.java
> +        for (Map.Entry<String, List<String>> entry : this.entrySet()) {
looks like an overcomplication, and it belongs to the business logic as well

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/model/TranslationMap.java
> +    private TranslationRequest createTranslationRequest(List<String> textsToTranslate, String targetLanguage) {
Might be good to use a method that is able to set all available fields, or even better use a builder pattern for the request. Eventually a Builder can be add to the TranslationRequest object itself

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/model/TranslationMap.java
> +        ComparatorUtils.removeDuplicates(translationsForField);
If removing nulls and dupplicates is a requirement, probably it is better to use a SortedSet/TreeSet than a list

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/service/BaseService.java
> +    public static Function<String, Map<String, List<String>>> getValueOfTheField(Proxy proxy, boolean update) {
when update=true, this is not a getter method anymore, not sure if it is good to combine getting the value with the setting of the field value. Anywy, the method name should indicate clearly the behaviour

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/service/BaseService.java
> +public class BaseService {
these look like post-pocessing services, not client services. Would be good to place them in other module. Not even sure if these classes should be placed in this repository...

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/utils/TranslationClientUtils.java
> +    public static Function<UriBuilder, URI> buildUrl(String path) {
not sure if this is meant to be reused, looks like being apropriate move as protected method in TranslationApiClient

2023-12-13 16:09 UTC, gsergiu commented on translation-definitions/src/main/java/eu/europeana/api/translation/definitions/language/Language.java
> +    public static final String PIVOT = Language.EN.name().toLowerCase(Locale.ROOT);
it is still the EnglishLanguage, the PIVOT has a meaning only for post.-processing but not for the translation/detection services

2023-12-13 16:09 UTC, gsergiu commented on translation-definitions/src/main/java/eu/europeana/api/translation/definitions/language/Language.java
> +    public static final String PIVOT = Language.EN.name().toLowerCase(Locale.ROOT);
I would recommend to change back to english

2023-12-13 16:09 UTC, gsergiu commented on translation-definitions/src/main/java/eu/europeana/api/translation/definitions/model/LangDetectRequest.java
> +package eu.europeana.api.translation.definitions.model;
I would put the request and response classes to eu.europeana.api.translation.definitions.web.model package

2023-12-13 16:09 UTC, gsergiu commented on translation-definitions/src/main/java/eu/europeana/api/translation/definitions/model/TranslationString.java
> +public class TranslationString {
it is not a String anymore, but a proper object. Probably better to keep Translation or EuropeanaTranslation

2023-12-13 16:09 UTC, gsergiu commented on translation-web/src/main/java/eu/europeana/api/translation/web/service/TranslationWebService.java
> +    List<TranslationString> translObjs = buildTranslationObjectList(translationRequest);
the field name should be updated after reamig the type. simply translations might be more appropriate

2023-12-13 16:09 UTC, gsergiu commented on translation-definitions/src/main/java/eu/europeana/api/translation/definitions/language/Language.java
> +    public static final String PIVOT = Language.EN.name().toLowerCase(Locale.ROOT);
also ... according to the requirements in the ticket, "the pivot language (English) should be configurable at startup", so ... definitely this constant should not be named as PIVOT

2023-12-13 16:09 UTC, gsergiu commented on translation-client/src/main/java/eu/europeana/api/translation/client/service/BaseService.java
> +public class BaseService {
We should probalby have an own repository for post-processing, different that the translation API, but I don't mind to have an own module here for the time being.

2023-12-18 14:41 UTC, SrishtiSingh-eu commented on translation-client/pom.xml
> +            <artifactId>corelib-definitions</artifactId>
moved to a different module

2023-12-18 14:45 UTC, SrishtiSingh-eu commented on translation-client/src/main/java/eu/europeana/api/translation/client/config/TranslationClientConfiguration.java
> +        try { properties = new Properties();
done

2023-12-18 14:46 UTC, SrishtiSingh-eu commented on translation-client/src/main/java/eu/europeana/api/translation/client/exception/TranslationApiException.java
> +        return HttpStatus.INTERNAL_SERVER_ERROR;
Changed it to runtime Exception

2023-12-18 14:47 UTC, SrishtiSingh-eu commented on translation-client/src/main/java/eu/europeana/api/translation/client/model/TranslationMap.java
> +public class TranslationMap extends LinkedHashMap<String, List<String>> {
Let's leave it like this for now. As i have to yet implement search translations. This would change in any case

2023-12-18 14:48 UTC, SrishtiSingh-eu commented on translation-client/src/main/java/eu/europeana/api/translation/client/model/TranslationMap.java
> +    public TranslationMap translate(TranslationApiClient translationApiClient, String targetLanguage) throws TranslationApiException {
Let's leave it like this for now. As i have to yet implement search translations.

2023-12-18 14:49 UTC, SrishtiSingh-eu commented on translation-client/src/main/java/eu/europeana/api/translation/client/model/TranslationMap.java
> +        for (Map.Entry<String, Integer> entry : textsPerField.entrySet()) {
SR translations are different as we need to keep track of the fields from where the data came and also we have to append them in another proxy in the same field. Data is collected from different proxies

2023-12-18 14:51 UTC, SrishtiSingh-eu commented on translation-definitions/src/main/java/eu/europeana/api/translation/definitions/language/Language.java
> +    public static final String PIVOT = Language.EN.name().toLowerCase(Locale.ROOT);
This is something Hugo asked. So please discuss with him

2024-01-10 12:57 UTC, P-Ehlert reviewed
There are one or two minor issues, but I'll already merge code.
We do need to work soon on improving code quality (sonar issues).

2024-01-10 12:57 UTC, P-Ehlert commented on pom.xml
> +		<corelib.version>2.16.7-SNAPSHOT</corelib.version>
Can be removed

2024-01-10 12:57 UTC, P-Ehlert commented on translation-client/src/main/java/eu/europeana/api/translation/client/BaseTranslationApiClient.java
> +    private static final int maxInMemSizeMb = 10;
Sonar warning about naming convention

2024-01-10 12:57 UTC, P-Ehlert commented on translation-client/src/main/java/eu/europeana/api/translation/client/service/TranslationApiRestClient.java
> +                        response -> response.bodyToMono(String.class).map(ExternalServiceException::new));
We should probably do this for all 5xx errors not only Bad gateway

2024-01-10 13:11 UTC, SrishtiSingh-eu commented on translation-client/src/main/java/eu/europeana/api/translation/client/BaseTranslationApiClient.java
> +    private static final int maxInMemSizeMb = 10;
done

2024-01-10 13:11 UTC, SrishtiSingh-eu commented on pom.xml
> +		<corelib.version>2.16.7-SNAPSHOT</corelib.version>
done

2024-01-10 14:08 UTC, gsergiu commented
> There are one or two minor issues, but I'll already merge code. We do need to work soon on improving code quality (sonar issues).

Well ... I see that my objection of Renaming the TranslationObj to TranslationString was not addressed ... not really happy with the change of the class name ...

2024-01-12 09:28 UTC, merged