track cache usage
europeana/translation-api pull request #69
Opened 2024-11-06 11:16 UTC by SrdjanStevanetic

2024-11-27 10:21 UTC, gsergiu requested changes

2024-11-27 10:21 UTC, gsergiu commented on translation-tests/src/integration-test/java/eu/europeana/api/translation/tests/web/TranslationRestIT.java
> +//        .andExpect(status().isOk())
any reason why this was commented out?

2024-11-27 10:21 UTC, gsergiu commented on translation-tests/src/integration-test/java/eu/europeana/api/translation/tests/BaseTranslationTest.java
> +  protected final static int redisPort=16370;
we should add redis test container to integration tests within the scope of this ticket (similar to mongo container is set api) https://testcontainers.com/modules/redis/

2024-11-27 10:21 UTC, gsergiu commented on translation-web/src/main/java/eu/europeana/api/translation/web/service/CachedTranslationService.java
> +    //logging the number of translated/cached lines and chars
please move the logging part to own method and use a java object to collect the metrics, e.g. TranslationCashingStats.

2024-11-27 10:21 UTC, gsergiu commented on translation-web/src/main/java/eu/europeana/api/translation/web/service/CachedTranslationService.java
> +    if(logger.isInfoEnabled()) {
if the metrics are not logs, their computation is redundand, please update acordingly.

2024-11-27 10:21 UTC, gsergiu commented on translation-web/src/main/java/eu/europeana/api/translation/web/service/CachedTranslationService.java
> +    int numCharsTranslated=toTranslate.stream().map(el -> el.getText().length()).reduce(0, Integer::sum);
this is incorectly computed, as it must not include the texts discarded for translation (i.e. nonTranslatable & same language)

2024-11-27 10:21 UTC, gsergiu commented on translation-web/src/main/java/eu/europeana/api/translation/web/service/CachedTranslationService.java
> +    int numCharsCached=translationObjs.stream().filter(el -> el.isRetrievedFromCache()).map(el -> el.getTranslation().length()).reduce(0, Integer::sum);
for performance reasons it is better to use a regular for loop, in which both the lines and the chars are computed.

2024-11-27 10:21 UTC, gsergiu commented on translation-web/src/main/java/eu/europeana/api/translation/web/service/CachedTranslationService.java
> +    int numCharsCached=translationObjs.stream().filter(el -> el.isRetrievedFromCache()).map(el -> el.getTranslation().length()).reduce(0, Integer::sum);
the computation of the lines and chars server by the translation service must be computed as well, 
see last row in the comment: https://europeana.atlassian.net/browse/EA-3969?focusedCommentId=133237

2024-12-02 16:03 UTC, SrdjanStevanetic commented on translation-tests/src/integration-test/java/eu/europeana/api/translation/tests/web/TranslationRestIT.java
> +//        .andExpect(status().isOk())
Removed, it works fine.

2024-12-16 20:23 UTC, merged